Support Laravel 11.x
akaunting/laravel-money pull request #97
Opened 2024-03-09 22:05 UTC by SupianIDz

- Add PHP 8.2
- Support Laravel 11

2024-03-10 08:58 UTC, lloricode commented
can you update GitHub action as well?

2024-03-10 20:44 UTC, SupianIDz commented
> can you update GitHub action as well?

There are some dev dependencies that still haven't updated to PHP 8.2, I think it's better to wait a little longer for the merge.

At least, this solves the problem temporarily.

2024-03-10 23:17 UTC, lloricode commented
hmm, also can you add php 8.3 on test? then exclude php8.1 on laravel 11

2024-03-10 23:37 UTC, SupianIDz commented
Sure, PHP 8.1 is already excluded from Laravel 11.

2024-03-11 16:01 UTC, lloricode requested changes
please add php8.3 on test, thank you

2024-03-11 16:02 UTC, lloricode requested changes
please add php8.3, thank you

2024-03-11 23:02 UTC, lloricode approved these changes

2024-03-14 13:22 UTC, ariaieboy commented
cc: @denisdulici

2024-03-15 21:35 UTC, andreeastrattner commented
Would appreciate laravel 11 support. Currently, this package is a blocker.

2024-03-15 21:51 UTC, denisdulici commented
@SupianIDz Please revert the PHP version change so I can merge the PR.

2024-03-15 21:59 UTC, SupianIDz commented
@denisdulici done

2024-03-16 17:17 UTC, SupianIDz commented
Do you mean stay on PHP 8.0? I thought only PHP 8.3 was reverted.

2024-03-16 17:17 UTC, SupianIDz commented
Do you mean stay on PHP 8.0? I thought only PHP 8.3 was reverted.

2024-03-17 00:28 UTC, ariaieboy commented
> Do you mean stay on PHP 8.0? I thought only PHP 8.3 was reverted.

You don't need to specify each PHP version on composer.json 
`^8.0|^8.1|^8.2` == `^8.0`

change composer.json PHP version to `^8.0` and add PHP 8.3 to test workflow file.

2024-03-17 00:47 UTC, SupianIDz commented
> > Do you mean stay on PHP 8.0? I thought only PHP 8.3 was reverted.
> 
> You don't need to specify each PHP version on composer.json `^8.0|^8.1|^8.2` == `^8.0`
> 
> change composer.json PHP version to `^8.0` and add PHP 8.3 to test workflow file.

Ahh, I just found out after looking deeper, thanks for the insight.

2024-03-17 00:48 UTC, SupianIDz commented
It has been updated, please check.

2024-03-17 09:54 UTC, ariaieboy commented
@denisdulici

2024-03-17 10:20 UTC, denisdulici commented on .github/workflows/tests.yml
>          laravel: [9.*, 10.*]
Please add 11 here.

2024-03-17 10:25 UTC, lloricode requested changes
please squash all commits

2024-03-17 11:39 UTC, SupianIDz commented
> please squash all commits

done.

----

@denisdulici PHP 8.3 has been added to Matrix, and excluding for PHP 8.0 & PHP 8.1 in Laravel 11.

But I saw that there was a test error related to "mock", I'm not very good at mocking.

Thank you for the assistance and new insights about versioning.

2024-03-17 12:02 UTC, lloricode approved these changes
thank you :beers:

2024-03-17 12:03 UTC, ariaieboy commented
the `Pslam` version 4 is not compatible you should add `Pslam` version 5.

2024-03-19 09:15 UTC, patriktoth67 commented
When can we expect the laravel 11 integration? At the moment this package is the last one preventing me from upgrading.

2024-03-19 16:35 UTC, SupianIDz commented
For those who want to need a quick solution while waiting.

```json
"repositories": [
    {
        "url": "https://github.com/SIOPENHSS/laravel-money.git",
        "type": "git"
    }
],
"require": {
     "akaunting/laravel-money": "master"
}
```

cc : @andreeastrattner @patriktoth67

2024-03-19 17:59 UTC, closed without merging

2024-03-19 17:59 UTC, denisdulici commented
Tests failed, so the current PR is not stable. I'll merge this https://github.com/akaunting/laravel-money/pull/98 PR and release a new version today.